ДЗ 3 Шемякин Никита
itmo2022-verstka/task-3 pull request #1
Opened 2022-12-06 14:01 UTC by JelluSandro

2023-01-06 17:36 UTC, trixartem requested changes
- ❌ Первая буква первого параграфа в статье обычно заметно выделяется
- ❌ А текст разбивается на колонки (минимум 4 на страницу)
- ❌ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
- ❌ Часто в тексте выделяют цитаты
- ✅ Обычно используют много разных нестандартных шрифтов (хотя бы три)
- ❌ В тексте используются переносы
- ❌ Изредка текст пишут вертикально
- ✅ Доп задание

2023-01-06 17:36 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  background-color: lightyellow;
лучше использовать hex или rgba

2023-01-06 17:36 UTC, trixartem commented on delorean-dmc-12/src/index.html
> +      <img class="img_check" src="imgs/checkbox.jpg" alt="checkbox">
Не хватает атрибута alt

2023-01-06 17:36 UTC, trixartem commented on delorean-dmc-12/src/index.html
> +      <img class="img_check" src="imgs/checkbox.jpg" alt="checkbox">
Лучше у каждой кнопки сделать иконку, которая говорит о том, что она делает

2023-01-08 19:47 UTC, JelluSandro commented
добавил отсутсвующие пункты, добавил иконки для значков и alt для img

2023-01-09 20:22 UTC, trixartem commented
✅ принято

2023-01-09 20:22 UTC, closed without merging