ДЗ 3
itmo2022-verstka/task-3 pull request #14
Opened 2023-01-07 04:16 UTC by SunsetMT

2023-01-23 20:40 UTC, trixartem requested changes
✅ Первая буква первого параграфа в статье обычно заметно выделяется
❌ А текст разбивается на колонки (минимум 4 на страницу)
❌ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
✅ Часто в тексте выделяют цитаты
❌ Обычно используют много разных нестандартных шрифтов (хотя бы три)
❌ В тексте используются переносы
✅ Изредка текст пишут вертикально
❌ Доп задание

2023-01-23 20:40 UTC, trixartem commented on delorean-dmc-12/src/index.html
> +      <div class="col-text-standard">
Не хватает семантики

2023-01-23 20:40 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +.col:nth-child(4n + 2) {
Пустые селекторы

2023-01-26 19:20 UTC, trixartem requested changes
✅ Первая буква первого параграфа в статье обычно заметно выделяется
❌ А текст разбивается на колонки (минимум 4 на страницу)
✅ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
✅ Часто в тексте выделяют цитаты
✅ Обычно используют много разных нестандартных шрифтов (хотя бы три)
❌ В тексте используются переносы
✅ Изредка текст пишут вертикально
❌ Доп задание

2023-01-26 19:20 UTC, trixartem commented on delorean-dmc-12/src/index.html
> +      <div class="col-text-standard">
Здесь подходит тег p

2023-01-26 19:22 UTC, SunsetMT commented
Я немного не понимаю задания видимо. Cколько у меня сейчас колонок? Переносы без знака переноса не считаются?

2023-01-26 19:24 UTC, trixartem commented
- Колонки имеются в виду текстовые колонки текста, как в газетах, когда текст перетекает в следующую колонку
- Переносы - использование тегов p и br

2023-01-26 19:25 UTC, SunsetMT commented
у меня есть еще завтрашний день до вечера на фиксы?

2023-01-27 20:17 UTC, trixartem commented
✅ Принято

2023-01-27 20:17 UTC, closed without merging