Купчик Антон
itmo2022-verstka/task-3 pull request #16
Opened 2023-01-09 21:13 UTC by tattosha01

DeLorean

2023-03-15 20:09 UTC, trixartem requested changes
✅ Первая буква первого параграфа в статье обычно заметно выделяется
❌ А текст разбивается на колонки (минимум 4 на страницу)
❌ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
❌ Часто в тексте выделяют цитаты
✅ Обычно используют много разных нестандартных шрифтов (хотя бы три)
❌ В тексте используются переносы
❌ Изредка текст пишут вертикально
❌ Доп задание. Нет размера шрифта

2023-03-15 20:09 UTC, trixartem commented on delorean-dmc-12/src/index.html
> +        Lorem newspaper
не хватает семантики

2023-03-19 19:04 UTC, tattosha01 commented on delorean-dmc-12/src/index.html
> +        Lorem newspaper
Исправил

2023-03-19 19:48 UTC, tattosha01 commented
> ✅ Первая буква первого параграфа в статье обычно заметно выделяется ❌ А текст разбивается на колонки (минимум 4 на страницу) ❌ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок) ❌ Часто в тексте выделяют цитаты ✅ Обычно используют много разных нестандартных шрифтов (хотя бы три) ❌ В тексте используются переносы ❌ Изредка текст пишут вертикально ❌ Доп задание. Нет размера шрифта

- У меня же ровно четыре колонки... :( ❔
- Добавил картинку ✅
- Добавил цитаты (кавычки с символами &#10077 и &#10078) ✅
- Добавил переносы в четвертую колонку ✅
- Немного не понял про вертикальный текст. Разве у меня не так, как надо? (пример газеты с вертикальным текстом https://oir.mobi/uploads/posts/2019-12/1576100428_25-43.jpg) ❔
- Да, пропустил как-то. Добавил выбор размера текста для доп.задания ✅

2023-03-22 20:24 UTC, trixartem commented
✅ Принято

2023-03-22 20:24 UTC, closed without merging