task3 solution
itmo2022-verstka/task-3 pull request #3
Opened 2022-12-06 21:16 UTC by Klanick

2023-01-06 17:55 UTC, trixartem requested changes
- ✅ Первая буква первого параграфа в статье обычно заметно выделяется
- ❌ А текст разбивается на колонки (минимум 4 на страницу)
- ✅ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
- ✅ Часто в тексте выделяют цитаты
- ❌ Обычно используют много разных нестандартных шрифтов (хотя бы три)
- ✅ В тексте используются переносы
- ✅ Изредка текст пишут вертикально
- ❌ Доп задание

2023-01-06 17:55 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  left: calc(-8px - 3px/2);
Что это за вычисления?

2023-01-06 17:55 UTC, trixartem commented on delorean-dmc-12/src/index.html
> +      <div class="caption">Pets Newspaper</div>
h1 ?

2023-01-07 08:20 UTC, Klanick commented
> * ❌ Обычно используют много разных нестандартных шрифтов (хотя бы три)
Не совсем понимаю почему этот критерий не выполнен (использовал шрифты Play, Montserrat Alternates, Oswald)

2023-01-07 08:25 UTC, Klanick commented
> * ❌ А текст разбивается на колонки (минимум 4 на страницу)
Тут мне казалось тоже выполнено. 
Возможно я, сделал что-то не так? Тогда правильно ли я понимаю, что от нас требуется, чтобы текст изначально был единым в html-разметке и каким-то образом автоматически сам разбивался на колонки?

2023-01-07 21:08 UTC, trixartem commented
> > * ❌ А текст разбивается на колонки (минимум 4 на страницу)
> >   Тут мне казалось тоже выполнено.
> >   Возможно я, сделал что-то не так? Тогда правильно ли я понимаю, что от нас требуется, чтобы текст изначально был единым в html-разметке и каким-то образом автоматически сам разбивался на колонки?

- Тут имеется в виду когда текст сам автоматические перетекает в следующую колонку, так же как в газетах

2023-01-07 21:09 UTC, trixartem commented
Жду фикс с колонками

2023-01-08 18:26 UTC, trixartem commented
✅ Принято

2023-01-08 18:26 UTC, closed without merging