Галибов Михаил Олегович М3339
itmo2022-verstka/task-3 pull request #4
Opened 2022-12-07 14:29 UTC by Gram3r

2023-01-08 18:25 UTC, trixartem requested changes
- ✅ Первая буква первого параграфа в статье обычно заметно выделяется
- ✅ А текст разбивается на колонки (минимум 4 на страницу)
- ✅ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
- ✅ Часто в тексте выделяют цитаты
- ✅ Обычно используют много разных нестандартных шрифтов (хотя бы три)
- ✅ В тексте используются переносы
- ❌ Изредка текст пишут вертикально
- ❌ Доп задание

2023-01-08 18:25 UTC, trixartem commented on delorean-dmc-12/src/index.html
> +            <div id="head">ПРАВДА</div>
Не хватает семантики

2023-01-08 18:25 UTC, trixartem commented on delorean-dmc-12/src/index.html
> +            <h1>Врачей много, а лечить некого</h1>
Почему h1?

2023-01-08 18:25 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +    grid-template-areas:
Ух как сложно

2023-01-08 18:25 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +#title {
А почему id? Лучше для стилей использовать классы и их уникальные имена - id'шник второй уже не добавишь

2023-01-08 18:25 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +#title {
Переделай, пожалуйста, на классы

2023-01-26 09:45 UTC, Gram3r commented on delorean-dmc-12/src/index.css
> +#title {
fixed

2023-01-26 09:46 UTC, Gram3r commented on delorean-dmc-12/src/index.css
> +    grid-template-areas:
fixed

2023-01-26 09:47 UTC, Gram3r commented on delorean-dmc-12/src/index.html
> +            <h1>Врачей много, а лечить некого</h1>
fixed

2023-01-26 09:53 UTC, Gram3r commented on delorean-dmc-12/src/index.html
> +            <div id="head">ПРАВДА</div>
fixed

2023-01-26 19:21 UTC, closed without merging