Потехин Денис
itmo2022-verstka/task-3 pull request #6
Opened 2022-12-07 21:09 UTC by DenisPotekhin2002

Решение Дз3

2023-01-08 18:48 UTC, trixartem requested changes
- ✅ Первая буква первого параграфа в статье обычно заметно выделяется
- ❌ А текст разбивается на колонки (минимум 4 на страницу)
- ❌ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
- ❌ Часто в тексте выделяют цитаты
- ✅ Обычно используют много разных нестандартных шрифтов (хотя бы три)
- ✅ В тексте используются переносы
- ✅ Изредка текст пишут вертикально
- ✅ Доп задание

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.html
> +  <div class="frontpage">
Мало семантики. См рекомендации к коду

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  z-index: 2;
Это точно нужно?

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +article b {
А почему не класс?

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +*,
Не очень хорошая практика для всех элементов менять свойства

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  margin: -21px 0 0 0;
Попробуй обойтись без отрицательного смещения

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  background-color: var(--article-color);
всем тегам p?

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  position: absolute;
А почему не просто border?

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  font-size: 130%;
лучше все таки px или rem ;)

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  z-index: 5;
А это зачем?

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  background-position: center;
Можно попробовать записать одним свойством - помогает запомнить

2023-01-08 18:48 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  font-size: 150%;
если хочется от родителя, то лучше em

2023-01-08 22:07 UTC, DenisPotekhin2002 commented
> * ✅ Первая буква первого параграфа в статье обычно заметно выделяется
> 
>     * ❌ А текст разбивается на колонки (минимум 4 на страницу)
> 
>     * ❌ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
> 
>     * ❌ Часто в тексте выделяют цитаты
> 
>     * ✅ Обычно используют много разных нестандартных шрифтов (хотя бы три)
> 
>     * ✅ В тексте используются переносы
> 
>     * ✅ Изредка текст пишут вертикально
> 
>     * ✅ Доп задание

а почему крестики на колонках, картинках с подписями и цитатах? У меня же все это есть. И картинок несколько с подписями, и колонок много, и цитаты в правом нижнем углу

2023-01-09 12:28 UTC, DenisPotekhin2002 commented on delorean-dmc-12/src/index.css
> +  z-index: 2;
уже и не помню, зачем это писал. Наверное, изначально хотел сделать какой-то неподвижный элемент, вроде футера или хедера, и хотел, чтобы ячейки всегда были поверх него - а в итоге не сделал. Да, похоже, что не нужно

2023-01-09 12:36 UTC, DenisPotekhin2002 commented on delorean-dmc-12/src/index.css
> +article b {
потому что без display:contents фрагменты с тэгом <b> становятся как бы прозрачными, на них не действует форматирование с белым фоном от родителя. А мне нужно, чтобы это форматирование применялось на все такие тэги, а не только на какие-то конкретные, выделенные по имени класса (например, у меня есть .f-l, обозначающий первую букву, но условно в надписи Official жирное всё, а не только первая буква. И мне не очень нравится идея давать имена всем <b> тэгам. Если в какой-то момент при добавлении нового забыть это сделать, будет некрасиво выглядеть на странице). Понимаю, что лукап по имени класса быстрее и эффективнее, чем по тэгу, но здесь писал b сознательно. Как и p чуть ниже - там мне нужно это применить ко всем параграфам любой статьи

2023-01-09 12:45 UTC, DenisPotekhin2002 commented on delorean-dmc-12/src/index.css
> +*,
но это нужно для всех элементов на странице) Селектор * не очень, действительно, да, понимаю. Поменяю на класс frontpage. Но это именно общие свойства, которые применяются ко всем ячейкам и ко всему тексту...

2023-01-09 13:02 UTC, DenisPotekhin2002 commented on delorean-dmc-12/src/index.css
> +  position: absolute;
мне нужно было, чтобы она выступала за границы блока на несколько пикселей, чтобы если рядом несколько блоков с fp-cell--border-top, у них была общая непрерывная верхняя граница, хотя между ними есть отступ. Просто border такого не умеет, кажется. Есть что-то такое у outline (outline-offset), но оно смещает не только влево-вправо, но и вверх-вниз, просто растягивает границу. + outline сразу вокруг всего блока. Есть еще box-shadow, но он тоже без оффсета влево-вправо от блока

2023-01-09 13:06 UTC, DenisPotekhin2002 commented on delorean-dmc-12/src/index.css
> +  z-index: 5;
Наверное, затем же, зачем и тот z-index. Хотел, чтобы заголовок был сверху при скроллинге - а в итоге сделал его не хедером, а просто частью страницы, не прибитой к верху. Уберу

2023-01-09 13:13 UTC, DenisPotekhin2002 commented on delorean-dmc-12/src/index.css
> +  font-size: 130%;
так мне же нужно, чтобы она была чуть больше окружающего текста. Странно будет делать в каждом параграфе первую букву одного размера в пикселях. Изменю на em

2023-01-09 13:14 UTC, DenisPotekhin2002 commented on delorean-dmc-12/src/index.css
> +  background-color: var(--article-color);
ой, это вообще что-то странное, тут и article не нужен, не то что p, достаточно просто .fp-item

2023-01-09 13:21 UTC, DenisPotekhin2002 commented on delorean-dmc-12/src/index.css
> +  margin: -21px 0 0 0;
а у frontpage можно? У body не очень, наверное, так делать, да, но вообще без отрицательного смещения там большой промежуток между верхом страницы и frontpage, который мне зрительно не нравится

2023-01-09 13:29 UTC, DenisPotekhin2002 commented on delorean-dmc-12/src/index.css
> +  position: absolute;
А, придумал, как сделать с просто border. Оказалось несложно

2023-01-10 12:33 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  margin: -21px 0 0 0;
Может занулить лишний отсутп?

2023-01-10 12:34 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  font-size: 130%;
em?

2023-01-10 12:37 UTC, trixartem commented
> а почему крестики на колонках, картинках с подписями и цитатах? У меня же все это есть. И картинок несколько с подписями, и колонок много, и цитаты в правом нижнем углу

1. У картинок нет подписей
2. Нет колонок текста, когда текст перетекает из одной колонки в другую

2023-01-10 12:40 UTC, DenisPotekhin2002 commented on delorean-dmc-12/src/index.css
> +  margin: -21px 0 0 0;
а, ой, я понял, в чём была проблема. Этот отступ не из-за марджинов-паддингов, а из-за невидимых радио-кнопок. Я случайно вместо display:none написал visibility:hidden. Сейчас исправлю

2023-01-10 12:44 UTC, DenisPotekhin2002 commented
> > а почему крестики на колонках, картинках с подписями и цитатах? У меня же все это есть. И картинок несколько с подписями, и колонок много, и цитаты в правом нижнем углу
> 
>     1. У картинок нет подписей
> 
>     2. Нет колонок текста, когда текст перетекает из одной колонки в другую

Я думал, имелось в виду что в принципе весь текст на странице разбит на колонки, а не что одна статья перетекает из блока в блок. С одной статьёй в двух блоках у меня есть где про миллионера, там оно обтекает картинку и начинается в 4 колонке, а продолжается в 2-4.
А что имеется в виду под подписями к картинкам, если не сопроводительный текст в соседнем блоке? Подпись прямо поверх изображения? В том же блоке, но ниже? Это же всё выглядит сильно хуже, чем с выносом заголовка в отдельный блок

2023-01-10 13:14 UTC, trixartem commented
> А что имеется в виду под подписями к картинкам, если не сопроводительный текст в соседнем блоке? 
Например подпись под картинкой. Там обычно пишут фотографа или название.

2023-01-10 13:15 UTC, trixartem commented
- ✅ Первая буква первого параграфа в статье обычно заметно выделяется
- ✅ А текст разбивается на колонки (минимум 4 на страницу)
- ✅ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
- ✅ Часто в тексте выделяют цитаты
- ✅ Обычно используют много разных нестандартных шрифтов (хотя бы три)
- ✅ В тексте используются переносы
- ✅ Изредка текст пишут вертикально
- ✅ Доп задание

2023-01-10 13:15 UTC, closed without merging