Смирнов Глеб M3339
itmo2022-verstka/task-3 pull request #8
Opened 2022-12-08 17:46 UTC by FireF0xIl

2023-01-09 20:35 UTC, trixartem requested changes
- ✅ Первая буква первого параграфа в статье обычно заметно выделяется
- ✅ А текст разбивается на колонки (минимум 4 на страницу)
- ❌ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
- ✅ Часто в тексте выделяют цитаты
- ❌ Обычно используют много разных нестандартных шрифтов (хотя бы три)
- ✅ В тексте используются переносы
- ✅ Изредка текст пишут вертикально
- ✅  Доп задание

2023-01-09 20:35 UTC, trixartem commented on delorean-dmc-12/src/index.html
> +        <span class="header-text">Кошачий вестник</span>
Не хватает семантики

2023-01-09 20:35 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  font-size: 2vw;
шрифт действительно должен зависеть от ширины экрана?

2023-01-09 20:35 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  border-bottom: 0.25vw solid;
а почему не px?

2023-01-09 20:35 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  font-size: 200%;
Лучше в em,rem,px

2023-01-09 20:35 UTC, trixartem commented on delorean-dmc-12/src/index.css
> +  border-left: 0.8vw solid;
Размеры бордеров лучше указывать фиксированными

2023-01-11 16:54 UTC, FireF0xIl commented on delorean-dmc-12/src/index.html
> +        <span class="header-text">Кошачий вестник</span>
fixed

2023-01-11 16:54 UTC, FireF0xIl commented on delorean-dmc-12/src/index.css
> +  font-size: 2vw;
fixed

2023-01-11 16:54 UTC, FireF0xIl commented on delorean-dmc-12/src/index.css
> +  border-bottom: 0.25vw solid;
fixed

2023-01-11 16:54 UTC, FireF0xIl commented on delorean-dmc-12/src/index.css
> +  font-size: 200%;
fixed

2023-01-11 16:54 UTC, FireF0xIl commented on delorean-dmc-12/src/index.css
> +  border-left: 0.8vw solid;
fixed

2023-01-11 16:59 UTC, FireF0xIl commented
> * ✅ Первая буква первого параграфа в статье обычно заметно выделяется
> * ✅ А текст разбивается на колонки (минимум 4 на страницу)
> * ❌ Есть, конечно, картинки и подписи к ним, иногда они занимают несколько колонок (ну хотя бы одно, которое занимает несколько колонок)
> * ✅ Часто в тексте выделяют цитаты
> * ❌ Обычно используют много разных нестандартных шрифтов (хотя бы три)
> * ✅ В тексте используются переносы
> * ✅ Изредка текст пишут вертикально
> * ✅  Доп задание

Добавил шрифты (для заголовков), колонки в центре под картинкой занимает несколько колонок, перетекание уже было

2023-01-15 10:34 UTC, trixartem commented
✅  Принято

2023-01-15 10:34 UTC, closed without merging